### ISSUE TITLE
Adatbázis véglegesítése, hány karakter lehessen a nyelv és a szó?

### ISSUE THREAD

**Issue by Lloydi50** [Geryson/DictAtOre#11]
Nekem jónak tűnik az AB, ha nektek nem megfelelő akkor szóljatok.

De ha megfelelő akkor Viktornak ezeket kéne megcsinálnia:
- a "Language" mezőnév nem tetszik az sqlite-nak ezért nevezd át "Language_id"-re vagy ha tudtok jobbat akkor arra
- a "Name" és a "Word" mezők karakter számát allítsd be

Ellenőrizd:
(elméletileg jónak kéne lennie mindennek, de mondtad(Viktor), hogy van olyan rekord ami duplán szerepel ugyanazzal az elsődleges kulccsal, ilyen ne történhessen meg)
- az elsődleges kulcs("id") mindkét táblában legyen: not null, auto increment
- a "Meaning" LEHESSEN null(arra az esetre ha egy szónak nincs jelentése, illetve nem vagyok benne biztos, de lehet, hogy új szó hozzáadása esetén problémát okozhat, hogy nem tudod meg adni a jelentését, mivel az még nem lesz benne az adatbázisba)
- a többi elméletileg jól van

**Comment by pictori** [comment]
egyetértek
