### ISSUE TITLE
Verziók halmozása a repository-n

### ISSUE THREAD

**Issue by Geryson** [Geryson/DictAtOre#14]
Máté felvetette Viberen, hogy a projekt egyes részeit külön is vissza lehet hozni, miután commitoltuk a változtatásokat; így nem kellene a különböző projektkönyvtárakat (0.0.1, 0.0.2, stb.) a repository-n tárolni (MÉRET). Én mondjuk ragaszkodnék hozzá, hogy maradjanak a projektkönyvtárak, mert nekem átláthatóbbnak tűnik, és valamivel biztonságosabbnak érzem (BIZTONSÁG).

De mindenképp el kell döntenünk, mi legyen, úgyhogy a régi változatok törlése mellett és ellen várok érveket.

**Comment by Lloydi50** [comment]
Csak egy változat legyen:
- felesleges minden módosításnál új néven elmenteni a projektet
- a verziókezelő pont ezért van, hogy ne kelljen manuálisan csinálni (szerintem ebből még baj lesz ha így csináljuk)
- szerintem egyáltalán nem átláthatóbb
- minden commitnál vissza lehet nézni a fájlok akkori állását
