### ISSUE TITLE
Adatbázis lekérdezési hibák

### ISSUE THREAD

**Issue by Geryson** [Geryson/DictAtOre#15]
Nem biztos, hogy sok lekérdezésben van hiba, de egyet már találtam is:

WordsSelect metódus futtatása SQLite-kivételt dob, mert a parancsban lévő Language_ID oszlopnév nem szerepel a Words táblában, nyelv-re módosítva megoldódik a probléma...

**Comment by pictori** [comment]
ennek oka az, hogy új adatbázis van mögé rakva, ahol már nem nyelv hanem Language_ID a mező név és ez is fog lenni későbbiekben is, így kérlek azt az adatbázist használd ( a régi elavult)
Amennyiben teszteléshez még a régi adatbázist szeretnéd használni, kérlek a 11_15-ös commitolási verziót szedd le
