### ISSUE TITLE
Új Activity-nevek

### ISSUE THREAD

**Issue by Geryson** [Geryson/DictAtOre#17]
Az átláthatóság kedvéért átneveznék pár Activity-t a következőkre:

- MainActivity --> FomenuActivity
- NyelvSettingActivity --> Nyelv_InsertActivity
- NyelvValaszto1Activity --> Nyelv_ChooseActivity

Jöhetnek az egyéb javaslatok, észrevételek is...

**Comment by Lloydi50** [comment]
Angol nevek legyenek szerintem.

**Comment by Geryson** [comment]
Akkor ez esetben a Tudástesztet elkereszteljük a kódban KnowledgeTest-nek? Mivelhogy ez is érintve lesz...

**Comment by Lloydi50** [comment]
Hát nem tudom, hogy ez-e a legjobb név, de igen.

**Comment by Geryson** [comment]
Akkor ezt túltárgyaltuk...
