### ISSUE TITLE
Módosítás és hozzáadás activity

### ISSUE THREAD

**Issue by pictori** [Geryson/DictAtOre#18]
Szerintem úgy kellene megoldani például a Language insert- és update-et, hogy ugyanarra az activityre mutassanak, de az activitynek továbbadnánk az információt, hogy melyik szolgáltatást kérte a felhasználó, így annak megfelelően járna el. pl.:
- insert esetében, úgy ahogy most van
- update esetében, a textboxot feltöltené azzal az adattal amit módosítani akarunk, az oké gombra kattintva pedig az update fgv-t hívná meg

**Comment by Lloydi50** [comment]
Valahol lehetne egy activity ami kilistázza a nyelveket és ott lehessen helyben hozzáadni és módosítani, meg törölni.
