### ISSUE TITLE
Rendezett lekérdezés

### ISSUE THREAD

**Issue by Geryson** [Geryson/DictAtOre#24]
Úgy gondolom, elegánsabb volna úgy megjeleníteni a nyelveket (később pedig a szavakat is), hogy azok ábécé-rendbe vannak rendezve... tudom, hogy néhány szót kell csak a parancsba írni...

"But that's none of my business..." ;D

**Comment by pictori** [comment]
ha szeretnétek megoldható, írok egy fgv-t ami a word objektumokat a word mező szerint rendez, és ugyanazt a word objektumot adja vissza immáron rendezve, és akkor elmondhatjuk hogy még egy rendező fgv is van benne, és tényleg illene egy szótárba abc sorrendet használni :D

**Comment by Lloydi50** [comment]
Alap, hogy abc sorrendbe kell lenniük a szavaknak. Szerintem én dolgom rendezni a szavakat.

**Comment by Geryson** [comment]
Oké, ahogy gondoljátok...(((És mondjuk az ORDER BY az SQL-parancsban nem lenne jó?)))

**Comment by pictori** [comment]
lehet hogy az is elég, ma kipróbálom, ha nem lesz elég akkor még ma megírom az abc fgv-t

**Comment by pictori** [comment]
most nézem a szavak már rendezve voltak eddig is, a nyelveket pedig rendezem az sql-ben, utána már máté dolga, ha netán keverődök valamilyen algoritmus hatására
