### ISSUE TITLE
A szótár kétirányú működése

### ISSUE THREAD

**Issue by Geryson** [Geryson/DictAtOre#26]
Feltűnt, hogy a szótárban a szavakat megjelenítő rész (a DictionaryList példányosítása környékén) a for ciklusban csak a másodlagos nyelv listájával művel valamit... akkor lett gyanús, amikor a spinnerekből új nyelv kiválasztásakor nem frissült minden, csak a másodlagos oldalon lévő lista (a funkción még dolgozok @ 12.03., 20:56)... márpedig ennek a kezelését jó lenne megoldani...

**Comment by pictori** [comment]
a FirstLanguageBundle és a SecondLanguageBundle értékét kellene frissítened Spinner változáskor
