### ISSUE TITLE
Helyes szó ellenőrzése a Tudástesztben?

### ISSUE THREAD

**Issue by Geryson** [Geryson/DictAtOre#3]
2 lehetőség:
- a megoldás textboxának tartalmát egy "Ellenőrzés" gombbal vizsgáljuk?
- vagy folyamatosan figyeljük a textbox tartalmát, és a helyes szó begépelése után egyből továbblépünk?

**Comment by Lloydi50** [comment]
Minden változáskor a textbox-ban(karakter törlése, új beírása), legyen egy ellenőrzés, addig amíg nincs meg a megoldás nem történik semmi, ha meg van a megoldás akkor pedig kiírjuk, hogy "Csodálatos vagy!" vagy, hogy "Fantasztikus vagy!" :D, vagy felugrik egy ablak(alert) és kiírjuk, hogy mi volt a szó és mi volt a felhasználó által beírt megoldás(mivel a felhasználó szeret gyönyörködni a "munkája" eredményében), illetve legyen egy "tovább" és "kilépés" gomb(esetleg egy olyan gomb ami kilistázza a többi helyes megfejtést).

**Comment by Geryson** [comment]
Az androidos TextWatcher osztály erre megfelel... rá lehet venni vele a progit, hogy figyelje folyton a szövegdobozt, utána egy bizonyos szövegnél azt csinálhatunk vele, amit akarunk...
