### ISSUE TITLE
Activityk csökkentésének megoldása

### ISSUE THREAD

**Issue by pictori** [Geryson/DictAtOre#5]
A Nyelv kiválasztás-t egy Activityvek kellene megoldani, amit többször hívunk. Két féle dolgot kellen le kezelni (tárolni), hogy egymás után hányszor hívjuk meg (---> nyelvek kiválasztásánal elmentése [a második meghívásnál az első nyelv törlése a listából]); a másik hogy tudáspróbából vagy szótárból van-e meghívva (szór esetében átszik az új nyelv gomb és aktív, tudáspróbánál nem látszik).

**Comment by Lloydi50** [comment]
Én a szótárhoz úgy gondolom ne legyen nyelv választó activity, hanem legyen két oszlop, az oszlopok fölött combobox amiből kilehet választani a nyelvet, illetve a bal és jobb oldali oszlopot lehessen külön jobbra és balra húzással lapozni(a nyelvek között lapozni).
Így már nem gond az, hogy egy activitybe rakjuk a nyelv választást a két helyen, mivel teljesen más megoldása lesz a kettőnek, persze csak akkor ha megfelelőnek találjátok a szótárat úgy ahogy én elképzeltem.

**Comment by pictori** [comment]
de ebben az esetben is a tudástesztnél 2 nyelvválasztó activity marad, amit meg lehet oldani hogy csak egyet keljen megcsinálni és azt kétszer meghívni, de ugyanúgy valahogy el kell tárolni az adatot hogy hányszor lett meghívva
a szótár esetében pedig hogy jelzed hogy a másik oszlopba már ne tudja kiválasztani azt a nyelvet amit az elsőben kiválasztott? ha csak az activity használata közben lehet frissíteni a lekérdezést és mondjuk a lekérdezésben lenne egy feltétel hogy ne lehessen benne a változóban eltárolt nyelv

**Comment by Lloydi50** [comment]
Akkor legyen egy activity a tudástesztnél ami úgy néz ki, hogy kilistázza a nyelveket és kitudod őket jelölni az 1. amit kijelölsz azon kapod a szót és a 2. kijelöltre kell fordítanod.
A szótár: A lekérdezés meg adja a nyelveket(ennyi a lekérdezés dolga), amit beleteszünk egy tömbbe vagy listába... most nem akarok elkezdeni gondolkozni rajta félórát, majd meg lesz oldva.

**Comment by Geryson** [comment]
Az utolsó szótáras gondolat jól működhet. Ha lekérdezed az összes nyelvet, eltárolod őket egy listában; ha kiválasztasz a 2 nyelvből 1-et, az törlődik a lekérdezés listájából, hogy ne lehessen onnantól még egyszer kiválasztani; ha pedig mindkettő ki lett választva, és te egy harmadikat jelölsz ki az egyik helyére, a régi és az új nyelv "helyet cserélnek".
