### ISSUE TITLE
segítség a felhasználónak

### ISSUE THREAD

**Issue by pictori** [Geryson/DictAtOre#9]
Egy rövid leírás a programról, és/vagy annak használatáról.
pl.: a Vagy a kezdő activityben (tudászteszt/ szótár választó) vagy állandóan minden activity valamely sarkában egy kis gomb vagy valami...

**Comment by Geryson** [comment]
Távoli funkció... csak akkor kell beleépíteni, ha már MI IS tudjuk, mi hogy működik majd...
